AWSTemplateFormatVersion: "2010-09-09"
Description: 
  create VPC and igw

Resources: 
  myVPC: 
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 192.168.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags: 
        - Key: Name
          Value: lesson-CFn-create-VPC

  myIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags: 
        - Key: Name
          Value: lesson-CFn-create-igw

  AttachGateway: 
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref myVPC
      InternetGatewayId: !Ref myIGW

  subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 192.168.0.0/24
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref myVPC
      Tags: 
        - Key: Name
          Value: lesson-CFn-create-Vpc-subnet-1a

  subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 192.168.1.0/24
      AvailabilityZone: ap-northeast-1c
      VpcId: !Ref myVPC
      Tags: 
        - Key: Name
          Value: lesson-CFn-create-Vpc-subnet-1c


